name = "mcp-memoria"
main = "worker.js"
compatibility_date = "2026-08-22"

[[d1_databases]]
binding = "DB"
database_name = "memoria-db"
database_id = "a37c3622-7b5b-444b-8a68-30db5a446d21"
# trigger build
